const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Keyboard,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.Arr,
		C3.Plugins.AJAX,
		C3.Plugins.PlatformInfo,
		C3.Plugins.LocalStorage,
		C3.Plugins.Dictionary,
		C3.Plugins.Audio,
		C3.Plugins.ConstructGameServices,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Behaviors.Timer,
		C3.Behaviors.Flash,
		C3.Behaviors.Sin,
		C3.Plugins.Browser,
		C3.Plugins.GM_SDK,
		C3.Plugins.GM_SDK.Cnds.PauseGame,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Acts.Shuffle,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetLayerEffectParam,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Touch.Cnds.OnNthTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Touch.Cnds.OnNthTouchEnd,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Arr.Exps.Height,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Behaviors.Sin.Cnds.IsEnabled,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Behaviors.Sin.Exps.Value,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.Arr.Exps.Back,
		C3.Plugins.Arr.Acts.Pop,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.ChildCount,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Plugins.Dictionary.Acts.SetKey,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Dictionary.Exps.AsJSON,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.ConstructGameServices.Acts.SubmitScore,
		C3.Plugins.GM_SDK.Acts.ShowAd,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Touch.Exps.TouchCount,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Exps.left,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Cnds.PickByHighestLowestValue,
		C3.Plugins.Sprite.Cnds.HasChildren,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.Arr.Cnds.IsEmpty,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Dictionary.Cnds.CompareValue,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.Text.Acts.SetPosToObject,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Acts.ScrollY,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.System.Exps.scrolly,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.SortZOrderByInstVar,
		C3.Plugins.LocalStorage.Cnds.IsProcessingGets,
		C3.Plugins.LocalStorage.Cnds.IsProcessingSets,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.Mouse.Cnds.OnAnyClick,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Audio.Acts.Stop
	];
};
self.C3_JsPropNameTable = [
	{Keyboard: 0},
	{Touch: 0},
	{Mouse: 0},
	{ArrSettings: 0},
	{AJAX: 0},
	{ArrOrders: 0},
	{PlatformInfo: 0},
	{LocalStorage: 0},
	{DictProfile: 0},
	{ArrTutorial: 0},
	{Audio: 0},
	{ArrBGM: 0},
	{ConstructGameServices: 0},
	{id: 0},
	{ButtonBox: 0},
	{ButtonContainer: 0},
	{ButtonCover: 0},
	{ButtonDough: 0},
	{ButtonTopping: 0},
	{ButtonMovementRight: 0},
	{ButtonTray: 0},
	{ButtonMovementLeft: 0},
	{Tween: 0},
	{ButtonExit: 0},
	{Counter: 0},
	{InGameInfo: 0},
	{Orders: 0},
	{TrayShelf: 0},
	{WaitingBox: 0},
	{WaitingLine: 0},
	{Wallpaper: 0},
	{Conveyor: 0},
	{busy: 0},
	{MachBox: 0},
	{MachContainer: 0},
	{MachCover: 0},
	{MachDough: 0},
	{MachTopping: 0},
	{MachLast: 0},
	{MachContainerBack: 0},
	{spotID: 0},
	{inUse: 0},
	{TraySpot: 0},
	{TraySpawn: 0},
	{productCode: 0},
	{UITraySpot: 0},
	{UIOrderSpot: 0},
	{currentSpot: 0},
	{hasContainer: 0},
	{isBoxed: 0},
	{Tray: 0},
	{Box: 0},
	{hasDough: 0},
	{numDoughs: 0},
	{invertZ: 0},
	{Container: 0},
	{Cover: 0},
	{Topping: 0},
	{doughNum: 0},
	{Dough: 0},
	{ContainerFront: 0},
	{spot: 0},
	{DoughSpot: 0},
	{UIContainer: 0},
	{UIContainerFront: 0},
	{UICover: 0},
	{UIDough: 0},
	{UITopping: 0},
	{UIBox: 0},
	{UIDoughSpot: 0},
	{TextApproved: 0},
	{TextRejected: 0},
	{TextTimer: 0},
	{TextGameOver: 0},
	{Timer: 0},
	{TextGameOverScore: 0},
	{starID: 0},
	{GameOverStarOff: 0},
	{GameOverStarOn: 0},
	{TextTutorial: 0},
	{TutorialPopupSpot: 0},
	{ButtonTutorial: 0},
	{currInstruction: 0},
	{TutorialPopup: 0},
	{TitleBackground: 0},
	{TitleForeground: 0},
	{TitleWorker: 0},
	{TitleBalloon: 0},
	{TitleText: 0},
	{Flash: 0},
	{Sine: 0},
	{TitlePressAnything: 0},
	{CurtainRight: 0},
	{CurtainLeft: 0},
	{MenuResetBtnNo: 0},
	{MenuResetBtnYes: 0},
	{hiddenY: 0},
	{MenuResetPopup: 0},
	{MenuBackground: 0},
	{yPos: 0},
	{parkedAt: 0},
	{MenuCar: 0},
	{parlorID: 0},
	{MenuParlor: 0},
	{MenuWaypoint: 0},
	{MenuBtnReset: 0},
	{MenuBtnSound: 0},
	{ParlorID: 0},
	{MenuStar: 0},
	{MenuTextEndless: 0},
	{CreditsCounter: 0},
	{TextCredits: 0},
	{TextCreditsBG: 0},
	{Sprite20: 0},
	{more: 0},
	{Browser: 0},
	{igraj: 0},
	{Sprite: 0},
	{lagged: 0},
	{GameMonetizeSDK: 0},
	{Machines: 0},
	{ParlorObject: 0},
	{TitleEntities: 0},
	{MenuZOrderables: 0},
	{approved: 0},
	{rejected: 0},
	{timeRemaining: 0},
	{canMoveConveyor: 0},
	{parlorSkin: 0},
	{timerTicking: 0},
	{gameOver: 0},
	{TXT_COLORS: 0},
	{size1: 0},
	{size2: 0},
	{size3: 0},
	{numBtns: 0},
	{unlockMovement: 0},
	{OK: 0},
	{ContainerUID: 0},
	{NEW_ORDER_X: 0},
	{NEW_ORDER_Y: 0},
	{ALL_CONTAINERS: 0},
	{ALL_DOUGHS: 0},
	{ALL_COVERS: 0},
	{ALL_TOPPINGS: 0},
	{ALL_BOXES: 0},
	{waitingBoxAnim: 0},
	{size: 0},
	{complexity: 0},
	{approvedCounter: 0},
	{WIN_TEXT: 0},
	{LOSE_TEXT: 0},
	{ENDLESS_TEXT: 0},
	{mode: 0},
	{justSpawnedUID: 0},
	{ORDER_SPOT_OFFSET: 0},
	{UIOrderSpotUID: 0},
	{level: 0},
	{pNoStars: 0},
	{mobileControls: 0},
	{canGoToMenu: 0},
	{audio: 0},
	{gotoLayout: 0},
	{CREDITS_SPEED: 0},
	{creditsDone: 0},
	{BGM_VOLUME: 0},
	{BGM_LOW_VOLUME: 0},
	{SFX_VOLUME: 0},
	{BGMPlayed: 0},
	{name: 0},
	{tag: 0},
	{volumeTweak: 0},
	{pitch: 0},
	{low: 0},
	{forceSilent: 0},
	{in: 0},
	{fadeTime: 0}
];

self.InstanceType = {
	Keyboard: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	ArrSettings: class extends self.IArrayInstance {},
	AJAX: class extends self.IInstance {},
	ArrOrders: class extends self.IArrayInstance {},
	PlatformInfo: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	DictProfile: class extends self.IDictionaryInstance {},
	ArrTutorial: class extends self.IArrayInstance {},
	Audio: class extends self.IInstance {},
	ArrBGM: class extends self.IArrayInstance {},
	ConstructGameServices: class extends self.IInstance {},
	ButtonBox: class extends self.ISpriteInstance {},
	ButtonContainer: class extends self.ISpriteInstance {},
	ButtonCover: class extends self.ISpriteInstance {},
	ButtonDough: class extends self.ISpriteInstance {},
	ButtonTopping: class extends self.ISpriteInstance {},
	ButtonMovementRight: class extends self.ISpriteInstance {},
	ButtonTray: class extends self.ISpriteInstance {},
	ButtonMovementLeft: class extends self.ISpriteInstance {},
	ButtonExit: class extends self.ISpriteInstance {},
	Counter: class extends self.ISpriteInstance {},
	InGameInfo: class extends self.ISpriteInstance {},
	Orders: class extends self.ISpriteInstance {},
	TrayShelf: class extends self.ISpriteInstance {},
	WaitingBox: class extends self.ISpriteInstance {},
	WaitingLine: class extends self.ISpriteInstance {},
	Wallpaper: class extends self.ISpriteInstance {},
	Conveyor: class extends self.ITiledBackgroundInstance {},
	MachBox: class extends self.ISpriteInstance {},
	MachContainer: class extends self.ISpriteInstance {},
	MachCover: class extends self.ISpriteInstance {},
	MachDough: class extends self.ISpriteInstance {},
	MachTopping: class extends self.ISpriteInstance {},
	MachLast: class extends self.ISpriteInstance {},
	MachContainerBack: class extends self.ISpriteInstance {},
	TraySpot: class extends self.ISpriteInstance {},
	TraySpawn: class extends self.ISpriteInstance {},
	UITraySpot: class extends self.ISpriteInstance {},
	UIOrderSpot: class extends self.ISpriteInstance {},
	Tray: class extends self.ISpriteInstance {},
	Box: class extends self.ISpriteInstance {},
	Container: class extends self.ISpriteInstance {},
	Cover: class extends self.ISpriteInstance {},
	Topping: class extends self.ISpriteInstance {},
	Dough: class extends self.ISpriteInstance {},
	ContainerFront: class extends self.ISpriteInstance {},
	DoughSpot: class extends self.ISpriteInstance {},
	UIContainer: class extends self.ISpriteInstance {},
	UIContainerFront: class extends self.ISpriteInstance {},
	UICover: class extends self.ISpriteInstance {},
	UIDough: class extends self.ISpriteInstance {},
	UITopping: class extends self.ISpriteInstance {},
	UIBox: class extends self.ISpriteInstance {},
	UIDoughSpot: class extends self.ISpriteInstance {},
	TextApproved: class extends self.ITextInstance {},
	TextRejected: class extends self.ITextInstance {},
	TextTimer: class extends self.ITextInstance {},
	TextGameOver: class extends self.ITextInstance {},
	TextGameOverScore: class extends self.ITextInstance {},
	GameOverStarOff: class extends self.ISpriteInstance {},
	GameOverStarOn: class extends self.ISpriteInstance {},
	TextTutorial: class extends self.ITextInstance {},
	TutorialPopupSpot: class extends self.ISpriteInstance {},
	ButtonTutorial: class extends self.ISpriteInstance {},
	TutorialPopup: class extends self.ISpriteInstance {},
	TitleBackground: class extends self.ISpriteInstance {},
	TitleForeground: class extends self.ISpriteInstance {},
	TitleWorker: class extends self.ISpriteInstance {},
	TitleBalloon: class extends self.ISpriteInstance {},
	TitleText: class extends self.ISpriteInstance {},
	TitlePressAnything: class extends self.ISpriteInstance {},
	CurtainRight: class extends self.ISpriteInstance {},
	CurtainLeft: class extends self.ISpriteInstance {},
	MenuResetBtnNo: class extends self.ISpriteInstance {},
	MenuResetBtnYes: class extends self.ISpriteInstance {},
	MenuResetPopup: class extends self.ISpriteInstance {},
	MenuBackground: class extends self.ISpriteInstance {},
	MenuCar: class extends self.ISpriteInstance {},
	MenuParlor: class extends self.ISpriteInstance {},
	MenuWaypoint: class extends self.ISpriteInstance {},
	MenuBtnReset: class extends self.ISpriteInstance {},
	MenuBtnSound: class extends self.ISpriteInstance {},
	MenuStar: class extends self.ISpriteInstance {},
	MenuTextEndless: class extends self.ITextInstance {},
	CreditsCounter: class extends self.ISpriteInstance {},
	TextCredits: class extends self.ITextInstance {},
	TextCreditsBG: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	more: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	igraj: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	lagged: class extends self.ISpriteInstance {},
	GameMonetizeSDK: class extends C3.Plugins.GM_SDK.Instance {},
	Machines: class extends self.ISpriteInstance {},
	ParlorObject: class extends self.ISpriteInstance {},
	TitleEntities: class extends self.ISpriteInstance {},
	MenuZOrderables: class extends self.ISpriteInstance {}
}