TEXT_SCORE     = "SCORE";
TEXT_ARE_SURE = "ARE YOU SURE?";
TEXT_GAMEOVER = "CONGRATULATION! YOU WON THIS MATCH!";
TEXT_LOSE = "PLAYER ";
TEXT_LOSE2 = " WON THIS MATCH";
TEXT_WIN_2PLAYERS = "PLAYER " ;
TEXT_WIN_2PLAYERS_2 = " WON THIS MATCH";
TEXT_SELECT_PLAYERS_MENU = "";
TEXT_NO_MOVES_AVAILABLE = "NO MOVES AVAILABLE, NEXT PLAYER WILL PLAY";
TEXT_DOUBLE_DICES = "GOT A DOUBLE, DICES REDOUBLED";
TEXT_THINKING = "";

TEXT_SHARE_IMAGE = "200x200.jpg";
TEXT_SHARE_TITLE = "Congratulations!";
TEXT_SHARE_MSG1 = "You collected <strong>";
TEXT_SHARE_MSG2 = " points</strong>!<br><br>Share your score with your friends!";
TEXT_SHARE_SHARE1 = "My score is ";
TEXT_SHARE_SHARE2 = " points! Can you do better";