const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.TextBox,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Fade,
		C3.Behaviors.Sin,
		C3.Plugins.Particles,
		C3.Plugins.Tilemap,
		C3.Behaviors.Pin,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Arr,
		C3.Plugins.Touch,
		C3.Plugins.Dictionary,
		C3.Plugins.Browser,
		C3.Plugins.GM_SDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.TextBox.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.TextBox.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.System.Cnds.OnLoadFailed,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Acts.LoadState,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Tilemap.Acts.SetOpacity,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.Width,
		C3.Behaviors.DragnDrop.Acts.Drop,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.GM_SDK.Acts.ShowAd,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Exps.Height,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SetZElevation,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.System.Acts.RestartLayout
	];
};
self.C3_JsPropNameTable = [
	{MoneyBackground: 0},
	{UpperBarBackground: 0},
	{Background: 0},
	{GoldIcon: 0},
	{HEADER_MONEY: 0},
	{HEADER_RestorantName: 0},
	{BUTTON_OK: 0},
	{NameTextEnter: 0},
	{Desvanecer: 0},
	{Spritefont_1: 0},
	{TalkBackground: 0},
	{OkButton: 0},
	{BlackBackground: 0},
	{Enbutton: 0},
	{EsButton: 0},
	{SpriteFont_2: 0},
	{Seno: 0},
	{Title: 0},
	{Pointer: 0},
	{Particles: 0},
	{TUTORIAL_TEXT: 0},
	{Deco_1: 0},
	{Pared_1: 0},
	{Pared_2: 0},
	{Garbage: 0},
	{Suelo_2: 0},
	{Suelo_3: 0},
	{Suelo_4: 0},
	{Suelo_1: 0},
	{Deco_2: 0},
	{Electrodomesticos_1: 0},
	{Pared_3: 0},
	{Pared_0: 0},
	{Deco_3: 0},
	{TV: 0},
	{Tables_1: 0},
	{Tables_2: 0},
	{ID: 0},
	{Walking: 0},
	{IsInTable: 0},
	{Happyness: 0},
	{Angry: 0},
	{Food_Recived: 0},
	{Food_Max: 0},
	{Points: 0},
	{WhatHeWants: 0},
	{WaitingTime: 0},
	{WaitingTimeMax: 0},
	{WaitingTimeOutAction: 0},
	{Speed: 0},
	{Table: 0},
	{Client_1: 0},
	{Client_2: 0},
	{Client_3: 0},
	{Client_4: 0},
	{Client_5: 0},
	{Client_6: 0},
	{Special_Client_1: 0},
	{Special_Client_2: 0},
	{Emotes: 0},
	{Money: 0},
	{Chef: 0},
	{Pegado: 0},
	{Food: 0},
	{FoodIndex: 0},
	{foodbutton: 0},
	{FoodMeter: 0},
	{COOKBUTTON: 0},
	{Client_Desires: 0},
	{Hueco_Comida: 0},
	{Calidad: 0},
	{En_Mesa: 0},
	{ArrastrarYSoltar: 0},
	{FinishedFood: 0},
	{SmokeParticles: 0},
	{HasFood: 0},
	{table_1: 0},
	{table_2: 0},
	{table_3: 0},
	{Ocupada: 0},
	{table_4: 0},
	{FoodStars: 0},
	{foodbutton2: 0},
	{FoodTimeArray: 0},
	{Touch: 0},
	{ES: 0},
	{EN: 0},
	{Upgrades_Deco: 0},
	{Upgrades_ground: 0},
	{Upgrades_wall: 0},
	{Upgrades_Tables: 0},
	{Upgrades_Cook: 0},
	{NextDayButton: 0},
	{Texto: 0},
	{TEXT_Deco_Cost: 0},
	{TEXT_Suelo_Cost: 0},
	{Text_walls_Cost: 0},
	{TEXT_Tables_cost: 0},
	{FoodBar: 0},
	{Logo: 0},
	{Browser: 0},
	{GameMonetizeSDK: 0},
	{Tables: 0},
	{Clientes: 0},
	{RestName: 0},
	{Money_show: 0},
	{LanguajeSelected: 0},
	{Tutorial_Step: 0},
	{Languaje: 0},
	{Showcook: 0},
	{DayTimer: 0},
	{FoodCooking: 0},
	{FoodDifficulty: 0},
	{Table_1: 0},
	{Table_2: 0},
	{Table_3: 0},
	{Table_4: 0},
	{SpecialChance: 0},
	{Room_decoration_satisfaction: 0},
	{Handicap: 0},
	{ClientTimer: 0},
	{FoodSlot_1: 0},
	{FoodSlot_2: 0},
	{FoodSlot_3: 0},
	{FoodSlot_4: 0},
	{day: 0},
	{IsCooking: 0},
	{QualityBonus: 0},
	{MaxRecipes: 0},
	{MoneyMultiplier: 0},
	{Food0_Times: 0},
	{Food1_Times: 0},
	{Food2_Times: 0},
	{Food3_Times: 0},
	{Table_lvl: 0},
	{Decoration_lvl: 0},
	{Ground_lvl: 0},
	{Wall_Lvl: 0},
	{Cook_lvl: 0},
	{Money_lvl: 0},
	{BarraXMov: 0},
	{BarraYMov: 0},
	{PointsWon: 0},
	{Quality: 0},
	{FoodID: 0},
	{FoodTime: 0},
	{MoneyValue: 0},
	{CLIENTE_ID: 0},
	{emote: 0},
	{RandomClient: 0},
	{RCFinished: 0},
	{SpecialOrNot: 0},
	{Cantiplatos_max_rnd: 0},
	{exigencianivel: 0},
	{Especial: 0},
	{rndfood: 0}
];

self.InstanceType = {
	MoneyBackground: class extends self.ISpriteInstance {},
	UpperBarBackground: class extends self.ISpriteInstance {},
	Background: class extends self.ISpriteInstance {},
	GoldIcon: class extends self.ISpriteInstance {},
	HEADER_MONEY: class extends self.ITextInstance {},
	HEADER_RestorantName: class extends self.ITextInstance {},
	BUTTON_OK: class extends self.ITextInstance {},
	NameTextEnter: class extends self.ITextInputInstance {},
	Spritefont_1: class extends self.ISpriteFontInstance {},
	TalkBackground: class extends self.ISpriteInstance {},
	OkButton: class extends self.ISpriteInstance {},
	BlackBackground: class extends self.ISpriteInstance {},
	Enbutton: class extends self.ISpriteInstance {},
	EsButton: class extends self.ISpriteInstance {},
	SpriteFont_2: class extends self.ISpriteFontInstance {},
	Title: class extends self.ISpriteInstance {},
	Pointer: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	TUTORIAL_TEXT: class extends self.ITextInstance {},
	Deco_1: class extends self.ITilemapInstance {},
	Pared_1: class extends self.ITilemapInstance {},
	Pared_2: class extends self.ITilemapInstance {},
	Garbage: class extends self.ISpriteInstance {},
	Suelo_2: class extends self.ITilemapInstance {},
	Suelo_3: class extends self.ITilemapInstance {},
	Suelo_4: class extends self.ITilemapInstance {},
	Suelo_1: class extends self.ITilemapInstance {},
	Deco_2: class extends self.ITilemapInstance {},
	Electrodomesticos_1: class extends self.ITilemapInstance {},
	Pared_3: class extends self.ITilemapInstance {},
	Pared_0: class extends self.ITilemapInstance {},
	Deco_3: class extends self.ITilemapInstance {},
	TV: class extends self.ISpriteInstance {},
	Tables_1: class extends self.ITilemapInstance {},
	Tables_2: class extends self.ITilemapInstance {},
	Client_1: class extends self.ISpriteInstance {},
	Client_2: class extends self.ISpriteInstance {},
	Client_3: class extends self.ISpriteInstance {},
	Client_4: class extends self.ISpriteInstance {},
	Client_5: class extends self.ISpriteInstance {},
	Client_6: class extends self.ISpriteInstance {},
	Special_Client_1: class extends self.ISpriteInstance {},
	Special_Client_2: class extends self.ISpriteInstance {},
	Emotes: class extends self.ISpriteInstance {},
	Money: class extends self.ISpriteInstance {},
	Chef: class extends self.ISpriteInstance {},
	Food: class extends self.ISpriteInstance {},
	foodbutton: class extends self.ISpriteInstance {},
	FoodMeter: class extends self.ISpriteInstance {},
	COOKBUTTON: class extends self.ISpriteInstance {},
	Client_Desires: class extends self.ISpriteInstance {},
	FinishedFood: class extends self.ISpriteInstance {},
	SmokeParticles: class extends self.IParticlesInstance {},
	table_1: class extends self.ISpriteInstance {},
	table_2: class extends self.ISpriteInstance {},
	table_3: class extends self.ISpriteInstance {},
	table_4: class extends self.ISpriteInstance {},
	FoodStars: class extends self.ISpriteInstance {},
	foodbutton2: class extends self.ISpriteInstance {},
	FoodTimeArray: class extends self.IArrayInstance {},
	Touch: class extends self.IInstance {},
	ES: class extends self.IDictionaryInstance {},
	EN: class extends self.IDictionaryInstance {},
	Upgrades_Deco: class extends self.ISpriteInstance {},
	Upgrades_ground: class extends self.ISpriteInstance {},
	Upgrades_wall: class extends self.ISpriteInstance {},
	Upgrades_Tables: class extends self.ISpriteInstance {},
	Upgrades_Cook: class extends self.ISpriteInstance {},
	NextDayButton: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	TEXT_Deco_Cost: class extends self.ITextInstance {},
	TEXT_Suelo_Cost: class extends self.ITextInstance {},
	Text_walls_Cost: class extends self.ITextInstance {},
	TEXT_Tables_cost: class extends self.ITextInstance {},
	FoodBar: class extends self.ISpriteInstance {},
	Logo: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	GameMonetizeSDK: class extends C3.Plugins.GM_SDK.Instance {},
	Tables: class extends self.ISpriteInstance {},
	Clientes: class extends self.ISpriteInstance {}
}